# -*- coding: utf-8 -*-
"""df_client.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pxC1Mxh4ftrvbR5m1MKLKvLusfZGHgtt

**Импорт библиотек**
"""

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

"""**Загрузка датасета**

*Описание данных:*

*user_data*:

**client** – идентификатор пользователя

**premium** – является ли клиент премиальным

**age** – возраст


*logs*:

**client** – идентификатор пользователя

**success** – результат (успех – 1, нет – 0)

**platform** – платформа

**time** – время в формате Unix

Отображение данных, размеров таблиц, типов переменных и описательной статистики.
"""

user_data = pd.read_csv('user_data.csv')
user_data.head()

user_data.shape

user_data.dtypes

user_data.describe()

logs = pd.read_csv('logs.csv')
logs.head()

logs.shape

logs.dtypes

logs.describe()

"""*Найти какой клиент (или клиенты) совершил больше всего успешных операций?*"""

max_succsess_client = logs.query("success == True").groupby('client', as_index=False).success.count().sort_values(['success', 'client'], ascending=False).head(20)

max_succsess_client[max_succsess_client.success == max_succsess_client.success.max()].client

"""Наибольшее количество успешных операций у клиентов с id: 12179, 28719, 36165, 52870, 61468, 61473, 78349, 82563, 92584

*Найти с какой платформы было совершено наибольшее количество успешных операций?*
"""

logs.query("success == True").groupby('platform', as_index=False).success.count().sort_values(['success', 'platform'], ascending=False).head(1)

"""Таким образом, наиболее популярной платформой среди успешных операций является - 'phone'.

*Найти какая платформа наиболее популярна среди премиумных клиентов?*

Объединение таблиц
"""

logs_data = logs.merge(user_data, how='inner', on='client')
logs_data.head()

"""Отбор по параметрам"""

logs_data.query("premium == True").groupby('platform', as_index=False).premium.count().sort_values(['premium', 'platform'], ascending=False)

"""Таким образом, наиболее популярной платформой среди преимиального класса является - 'phone'.

*Визуализируйте распределение возраста клиентов в зависимости от типа клиента (премиум или нет)*
"""

sns.distplot(logs_data.query('premium == True').age)
sns.distplot(logs_data.query('premium == False').age)

"""*Построение графика распределения числа успешных операций*"""

client_succsess = logs_data.groupby('client').agg({'success':'sum'})
sns.distplot(client_succsess, kde=False)

"""*Визуализация числа успешных операций, сделанных на платформе 'computer', в зависимости от возраста*"""

success_computer = logs_data.query("platform == 'computer' and success==True")
success_computer

plt.figure(figsize=(12, 8))
sns.countplot(success_computer.age)

"""Наибольшее количество успешных действий совершено клиентами в возрасте 28 лет."""